export enum PrivilageEnum {
  MANAGE_ORGANIZATION_EVENTS = 'MANAGE_ORGANIZATION_EVENTS',
  MANAGE_APPLICATIONS_FOR_ORGANIZATION_EVENTS = 'MANAGE_APPLICATIONS_FOR_ORGANIZATION_EVENTS',

  SEARCH_EVENTS = 'SEARCH_EVENTS',
  POSSIBILITY_TO_PARTICIPATE_IN_EVENTS = 'POSSIBILITY_TO_PARTICIPATE_IN_EVENTS'
};
